AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 120
    MemorySize: 128

    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Layers: 
        - !Ref ZohoBookApiLayer

  ZohoBookApiLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
        LayerName: ZohoBookApiLayer
        Description: My Lambda Layer with Deserialize Function, Objectpath Module & AWS Regions JSON
        ContentUri: zoho-book-api-layer/zoho-book-api-layer.zip
        CompatibleRuntimes:
            - python3.9
        LicenseInfo: MIT
        RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.9

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

# Outputs:
#     MyLambdaLayerARN:
#         Value: !Ref MyLambdaLayer
#         Description: MyLambdaLayer ARN
#         Export:
#             Name: my-lambda-layer-arn
